export const products = [
    {
        id: "1",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "2",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "3",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "4",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "5",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "6",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "7",
        image : "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "8",
        image : "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
    {
        id: "9",
        image : "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        title : "This is a product title",
        oldprice : "2500",
        newprice : "2400",
        pcksize : "21",
        estdelivery : "7",
        price : 2400,
        quantity: 1,
    },
  ];
  

 

  